REL_DESCRIPTIONS = {
    'en': {
        '/r/RelatedTo': 'related to',
        '/r/TranslationOf': 'translation of',
        '/r/FormOf': 'form of',
        '/r/Synonym': 'synonym of',
        '/r/Antonym': 'antonym of',
        '/r/HasContext': 'has context',
        '/r/DerivedFrom': 'derived from',
        '/r/IsA': 'is a',
        '/r/EtymologicallyRelatedTo': 'etymologically related to',
        '/r/AtLocation': 'location',
        '/r/Causes': 'causes',
        '/r/UsedFor': 'used for',
        '/r/MotivatedByGoal': 'motivated by goal',
        '/r/HasSubevent': 'has subevent',
        '/r/DistinctFrom': 'distinct from',
        '/r/SimilarTo': 'similar to',
        '/r/CapableOf': 'capable of',
        '/r/Desires': 'desires',
        '/r/PartOf': 'part of',
        '/r/HasPrerequisite': 'has prerequisite',
        '/r/CausesDesire': 'causes desire',
        '/r/HasProperty': 'has property',
        '/r/MadeOf': 'made of',
        '/r/HasFirstSubevent': 'has first subevent',
        '/r/HasLastSubevent': 'has last subevent',
        '/r/DefinedAs': 'defined as',
        '/r/ReceivesAction': 'receives action',
        '/r/HasA': 'has a',
        '/r/SymbolOf': 'symbolizes',
        '/r/NotDesires': 'does not desire',
        '/r/ObstructedBy': 'obstructed by',
        '/r/NotUsedFor': 'not used for',
        '/r/NotCapableOf': 'not capable of',
        '/r/Entails': 'entails',
        '/r/CreatedBy': 'created by',
        '/r/MannerOf': 'manner of',
        '/r/LocationOfAction': 'location of action',
        '/r/HasTheme': 'has theme',
        '/r/LocatedNear': 'located near',
        '/r/HasAgent': 'has agent',
        '/r/HasPatient': 'has patient',
        '/r/HasInstrument': 'has instrument',
    }
}
