conceptnet52:
    build: 'legacy'
    expose:
        - "10052"

conceptnet53:
    image: 'rspeer/conceptnet-web:5.3'
    expose:
        - "10053"
    volumes:
        - "/data/conceptnet:/conceptnet_data"
    ports:
        - "10053:10053"

conceptnet54:
    build: '.'
    expose:
        - "10054"
    volumes:
        - "/data/conceptnet5.4:/conceptnet_data"
    ports:
        - "10054:10054"

router:
    build: 'router'
    links:
        - "conceptnet52"
        - "conceptnet53"
        - "conceptnet54"
    volumes:
        - "/data/downloads:/var/www/downloads:ro"
        - "/data/nginx/cache:/data/nginx/cache"
    ports:
        - "80:80"

